---
title: "About me"
---

I am a retired Professor of Marketing at the Chinese University of Hong Kong. I taught Marketing Research, Quantitative Marketing, Internet Marketing and Chinese Wisdom and Marketing at both undergraduate and postgraduate levels. My current research interests are data analytics, complexity systems in marketing, and Chinese wisdom and marketing. 

**Publications in Refereed Academic Journals**
 
- Tian, V.-I., Tang, F. and Tse, A.C.B. (2022), "Understanding Chinese Hospitality Industry Employee Satisfaction and Marketing Performance from a Confucian Perspective", Journal of Quality Assurance in Hospitality & Tourism. https://www.tandfonline.com/doi/full/10.1080/1528008X.2022.2109237.
- Tian, V.-I., Tang, F. and Tse, A.C.B. (2021), "Understanding corporate culture and business performance from a Confucian perspective", Asia Pacific Journal of Marketing and Logistics. https://doi.org/10.1108/APJML-08-2020-0555.
- A. Au and A. Tse, 2021 "Customer Accounting: Antecedents, Consequences and Moderators," Harvard Deusto Business Research, Vol. 19, No. 1, https://doi.org/10.48132/hdbr.336. 
- Tian, VI., Tse, A.C.B. & Powpaka, S. 2020, Jun-zi orientation: unique aspects of Asian business practices. Asian J Bus Ethics. https://doi.org/10.1007/s13520-020-00116-5. 
- Ivan Arraut, Alan Au, Alan Ching-biu Tse, 2020 "Spontaneous symmetry breaking in quantum finance;" EPL (Europhysics Letters), Volume 131, Number 6. https://iopscience.iop.org/article/10.1209/0295-5075/131/68003.
- Vane Ing Tian , Alan K. M. Au & Alan C. B Tse 2020 "Impermanence Mindset and Market-Focused Dynamic Capability;" Journal of International Consumer Marketing, https://doi.org/10.1080/08961530.2020.1820418.
- Tse, A. 2019 "He is to be prized;" in Change is the Constant, eds. A. C. F. Chan and J. H.L. Ko, Infolink Publishing, pp. 95-116.
- Ivan Arraut, Alan Au, Alan Ching-biu Tse, Carlos Segovia, 2019 "The connection between multiple prices of an Option at a given time with single prices defined at different times: The concept of weak-value in quantum finance;" Phys. A, Vol. 526, 1-19.
- Alan Kai Ming Au and Alan Ching Biu Tse, 2019 "Expectancy disconfirmation: Effects of deviation from expected delay duration on service evaluation in the airline industry", Asia Pacific Journal of Marketing and Logistics, Vol. 31 Issue: 1, pp.291-300.
- Tian, Vane I., Felix Tang and Alan Tse, 2019, "All Hands on Deck: Personifying Socially Responsible Corporations: Scale Development and Validation", Academy of Marketing Science 2019 Conference.
- Tang, F., Tian, V.I., Tse, A. C. Biu, & Chee, E. 2016. How Confucius influences consumer’s view on socially responsible corporations. In Looking forward, looking back: Drawing on the past to shape the future of marketing (pp. 896-896). Springer International Publishing.
- SO, Lai Man Stella; KWOK Wai Yee Susanna and TSE Ching-biu Alan, 2010 "Skepticism Towards Product Placement: a Study on the Effectiveness of the Product Placement Execution". Paper presented in the 2010 Oxford Business & Economics Conference Program, organized by St. Hugh's College, Oxford University, Oxford, UK, 22 pgs. London, United Kingdom, 2010.06.
- Wendy W.N. Wan, Chung-Leung Luk, Oliver H.M. Yau, Alan C.B. Tse, Leo Y.M. Sin, Kenneth K. Kwong And Raymond P.M. Chow 2009 “Do Traditional Chinese Cultural Values Nourish a Market for Pirated CDs?” Journal of Business Ethics, Vol. 88, pp. 185-196.
- Luk, C. L., O. Yau, L. Sin, Tse, A., R. Chow, and J. Lee 2008 ” The Effects of Social Capital and Organizational Innovativeness in Different Institutional Contexts;” Journal of International Business Studies, Vol. 39, pp. 589-612.
- Chow, R., O. Yau, L. Sin, A. Tse, C. L. Luk and J. Lee, 2007, “Developing a Scale for Stakeholder Orientation;” European Journal of Marketing, Vol. 41, Numbers 11-12, 2 pp. 1306-1327.
- Yim Frederick Hong-kit, Tse Alan Ching-biu, Wong King Yin 2007 “Factors Affecting Mobile Commerce and Level of Involvement;” in Encyclopedia of Mobile Computing and Commerce, eds. David Tanier, Information Science Reference, pp. 283-90.
- Tse A., Tse K. C., Tse K. H., Au A., Tian V. I. 2007 “The Buddhist Theory of Impermanence and Marketing;” Innovative Marketing Vol.3, No. 2, pp.19-22.
- Tse, A. 2006 “Klesa is Bodhi: Acquiring Wisdom through Suffering;” The Buddhing Lotus, Vol. 1, pp. 166-171.
- Hui, M., A. Tse and L. Zhou 2006 “Interaction between Two Types of Information on Reactions to Delays;" Marketing Letters; Vol. 17, pp. 151-62. 
- Tse, A., S. So, L. Sin and K. H. Tse 2006 “Crisis management and recovery: How restaurants in Hong Kong responded to SARS?” International Journal of Hospitality Management, Vol. 25, pp. 3-11.
- Leo Y. M. Sin, Alan C. B. Tse, Haksin Chan, Vincent C. S. Heung, and Frederick H. K. Yim 2006 “The Effects of Relationship Marketing Orientation on Business Performance in the Hotel Industry;” Journal of Hospitality & Tourism Research 30: 407-426.
- Leo Y M Sin, Alan C B Tse, Frederick H K Yim, 2005 “CRM: conceptualization and scale development;” European Journal of Marketing, Vol.39, Iss. 11/12; pg. 1264-1290.
- Sin, L., A. Tse; O. Yau, J. Lee and R. Chow 2005 “Market Orientation, Relationship Orientation and Business Performance: The Moderating Effects of Economic Ideology and Industry Type;” Journal of International Marketing, Vol. 13, Iss. 1; p. 36-57.
Sin, L., Tse, A., V. Heung and F. Yim 2005 “An Analysis of the Relationship between Market Orientation and Business Performance in the Hotel Industry;” International Journal of Hospitality Management, Vol. 24, pp. 555-577.
- Tse, A., L. Sin, V. Heung and F. Yim 2005 “Market Orientation and Hotel Performance;” Annals of Tourism Research, vol. 52, No. 4, pp. 1145-1147.
- Tse, A., L. Sin, O. Yau, R. Chow, and J. Lee 2004 “A Firm’s Role in the Marketplace and the Relative Importance of Market Orientation and Relationship Marketing Orientation” European Journal of Marketing, Vol. 38, No. 9/10, 1158-1172.
- Luk, C. L., O. Yau, A. Tse; L. Sin and R. Chow 2005 “Stakeholder Orientation And Business Performance: The Case Of Service Compaines In China;” Journal of International Marketing, Vol. 13, No. 1, pp. 89-110.
- Sin, L., A. Tse, O. Yau, R. Chow, J. Lee and L. Lau 2005 “Relationship Marketing Orientation: Scale Development and Cross-Cultural Validation;” Journal of Business Research, Vol. 58, pp. 185-94.
- Tse, A. and C. F. Chan 2004 “The Relationship between Interactive Functions and Website Ranking;” Journal of Advertising Research, Vol. 44, No.4, pp. 369-374.
- Sin, L., A. Tse; O. Yau, J. Lee and R. Chow 2004 “Market Orientation and Business Performance in the PRC: A Regional Comparison;” Journal of Global Marketing, Vol. 17(2), pp. 55-90.
- Lee, Jenny S. Y., O. H. M. Yau, R,aymond Chow, Leo Y. M. Sin and A. Tse 2004 “Changing Roles and Values of the Female Consumers in China;” Business Horizon, Vol. 43, No. 3, pp. 17-22.
- Kwong, K. K. , Yau, O. H. M., Jenny S. Y. Lee, Leo Y. M. Sin and A. Tse 2003 “The Effects of Attitudinal and Demographic Factors on Intention to Buy Pirated CDs: The Case of Chinese Consumers;” Journal of Business Ethics, Vol. 47, pp. 223-35.
- Tse, A. 2003 “Tipping Behavior: A Discconfirmation of Expectation Perspective;” International Journal of Hospitality Management, Vol. 22, pp.461-67.
- Tse, A. 2003 “Disintermediation of Travel Agents in the Hotel Industry;” International Journal of Hospitality Management, Vol. 22, pp. 453-60.
- Chan, I. I.; A. Tse and F. Yim 2003 “Comparing and Combining Individual x-Charts and x-bar Charts;” International Journal of Quality & Reliability Management, Vol. 20, No. 7, pp. 827-35.
- Sin, L., A. Tse, O. Yau, R. Chow, and J. Lee 2003 “Market Orientation and Business Performance: A Comparative Study of Firms in Mainland China and Hong Kong;” European Journal of Marketing, Vol. 37, No. 5/6, pp. 910-36.
- Tse, A., Leo Y. M. Sin, Yau, O. H. M. Jenny S. Y. Lee and Raymond Chow 2003 "Relationship Between Market Orientation and Business Performance: An Empirical Study in a Chinese Business Environment;" Journal of Business Research, Vol. 56, pp. 227-39.
- Tse, A., F. Yim and K. H. Tse 2003 “Product Involvement and The Importance of Factors Affecting Mobile Commerce;” included in Intelligence Section, Sloan Management Review, Spring, Vol. 44, No. 3, pp. 9-10.
- Tse, A., Leo Y. M. Sin, Yau, O. H. M. Jenny S. Y. Lee and Raymond Chow 2002 "The Effect of Relationship Marketing Orientation on Business Performance in a Service-oriented Economy;" Journal of Services Marketing, Vol. 16, No.7, pp.656-676.
- Tse, A., Sin, L. and F. Yim 2002“How a Crowded Restaurant Affects Consumers’ Attribution Behaviour;” International Journal of Hospitality Management, Vol. 21, pp. 449-54.
- Sin, L. and A. Tse 2002 “Profiling Internet Shoppers in Hong Kong: Demographic, Psychographic, Attitudinal and Experiential Factors;” Journal of International Consumer Marketing, Vol. 15, No. 1, pp. 7-29.
- Tse, A. Tse, A. and Frederick Yim 2002 "How do Consumers Perceive Clear and Transparent Products?" International Journal of Commerce and Management, Vol. 12, No. 1, pp. 68-78.
- Tse, A. and F. Yim 2001 "Factors Affecting the Choice of Channels: Online vs. Conventional; " Journal of International Consumer Marketing, Vol. 14, No. 2/3, pp. 137-52.
- Tse, A. 2001 "Using Mathematical Programming to Solve Large Ranking Problems;" Journal of the Operational Research Society, Vol. 52, pp. 1144-50.
- Au, A. Au, A. and A. Tse, 2001 "Marketing Ethics and Behavioral Disposition of Chinese Managers of SMEs in Hong Kong;" Journal of Small Business Management, Vol. 39, Iss. 3; pg. 272-8.
- Tse A. and Ruby Lee 2001 "Zapping Behaviour During Commercial Breaks;" Journal of Advertising Research, Vol. 41, No. 3, pp. 25-30.
- Tse, A. 2001 "How Much More Are Consumers Willing to Pay for a Higher Level of Service - A Preliminary Survey;" Journal of Services Marketing, Vol. 15, No.1, pp. 11-7.
- Sin Y.M. Leo; Alan C.B. Tse; Oliver H.M. Yau; Jenny S.Y. Lee; Raymond Chow and Lorett B.Y. Lau 2000 "Market Orientation and Business Performance: An Empirical Study in Mainland China;" Journal of Global Marketing, pp. 5-30.
- Yau, O. H. M., Jenny S. Y. Lee, Raymond P. M. Chow, Leo Y. M. Sin, and A. Tse 2000 "Is Relationship Marketing for Everyone;" European Journal of Marketing, Vol. 35, pp. 1111-27.
- Sin, Leo and Alan C. B. Tse, 2000 "How does Marketing Effectiveness Mediate the Effect of Organizational Culture On Business Performance: The Case Of Service Firms;" Journal of Services Marketing, Vol. 14, No. 4 & 5, pp. 295-309.
- Yau, O. H. M., Jenny S. Y. Lee, Raymond P. M. Chow, Leo Y. M. Sin, and A. Tse, 2000 "Relationship Marketing - the Chinese Way;" Business Horizons, Jan-Feb, pp. 16-24.
- Tse, A. 1999 "Conducting Electronic Focus Group Discussions Among Chinese Respondents" Journal of the Market Research Society, Vol. 41, No.4, pp. 407-15.
- Tse, A. 1999 "Factors Affecting Consumer Perceptions on Product Safety - The Case of Nondurables;" The Journal of International Consumer Marketing, Vol. 12, No.1, pp.39-55.
- Tse, A. and C. I. Chan 1999 "Composite Ordinal Forecasting in Gaming - An Optimization Approach;" Gaming Research and Review Journal, Vol. 4, No. 1, pp. 81-9.
- Tse, A. 1999 "Factors Affecting Consumer Perceptions on Product Safety;" European Journal of Marketing, Vol. 33, No. 9/10, pp. 911-25.
- Tse, A. 1998 "Comparing the Response Rate, Response Speed and Response Quality of Two Methods of Sending Questionnaires: E-mail vs. Mail;" Journal of the Market Research Society, Vol. 40, No. 4, pp. 353-61.
- Tse, A. 1998 "An Empirical Investigation of the Correlational Relationship Between Market Orientation and Performance of Large Property Companies in Hong Kong;" International Journal of Commerce and Management, Vol. 8, No. 1, pp. 57-69.
- Tse, A. and A. Au 1997 "Are New Zealand Business Students More Unethical Than Non-Business Students?" Journal of Business Ethics, 16, pp. 445-50.
- Tse, A.; W. K. Chan, M. Y. Choi, W. Kwai and L. M. Lam 1996 "The Impact of Country-of-Origin on the Behaviour of Hong Kong Consumers;" Journal of International Marketing and Marketing Research, Vol. 21, No. 1, pp. 39-44.
- Au, Alan; A. Tse; K. K. Chan and W. S. Siu 1996 "Forecasting Political Systems Stability: A Study on the People's Republic of China;" International Journal of Management, Vol. 13, No. 1, pp. 60-7.
- Tse, A.; K. C. Tse; C.H. Y. Chow; B. T. Choy; Y. W. Ko; P. Y. Kwan and C. H. Wing 1995 "Comparing Two Methods of Sending Out Questionnaires: E-mail vs. Mail;" Journal of the Market Research Society, Vol. 37, No. 4, pp. 441-6.
- Tse, A. 1995 "Estimating the Design Factor for Surveys in Hong Kong;" Marketing Intelligence and Planning, Vol. 13, No. 9, pp. 28-9.
- Au, A. K. M. and A. Tse 1995 "The Effect of Marketing Orientation on Company Performance in the Service Sector: A Comparative Study of the Hotel Industry in Hong Kong and New Zealand;" Journal of International Consumer Marketing, Vol. 8(2), pp. 77-87.
- Au, Alan; A. Tse; W. K. Choi and C. M. Siu 1994 "The Effects of Technology on Perceived Risk Attitude Towards Extended Products in Brand Extension;" in Asia-Pacific Advances in Consumer Research, Vol. 1, eds. J. A. Cote and S. M. Leong, pp. 320-2.
- Tse, A.; A. Au; Ruby Ching; Yong Biao Ding; Ronald Fong and Eric Yeung 1994 "A Comparison of the Effectiveness of Mail and Facsimile as Survey Media on Response Rate, Speed and Quality;" Journal of the Market Research Society, October, Vol. 36(4), pp. 349-55.



